---
version: '3'
services:
  nifi:
    container_name: nifi 
    build:
      context: .
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8080:8080"
        #- "3306:3306"
        # network_mode: "host"
        #environment:

