FROM apache/nifi:1.8.0
RUN wget https://cdn.mysql.com/archives/mysql-connector-java-8.0/mysql-connector-j-8.0.33.tar.gz && \
	tar -xf mysql-connector-j-8.0.33.tar.gz && \
	cp mysql-connector-j-8.0.33/mysql-connector-j-8.0.33.jar /opt/nifi/nifi-current/lib && \
	rm -rf mysql-connector-j-8.0.33*
