# Zeppelin 0.11.1 Docker compose 

version: '1.0'

services:
  zeppelin:
    #image: apache/zeppelin:0.11.1
    container_name: zeppelin
    build:
      context: .
      dockerfile: Dockerfile
    user: ${UID}:${GID}  
    ports:
      - "8082:8080"
      - "4042-4043:4040-4041"
    volumes:
      - ./notebook:/opt/zeppelin/notebook
      - ./logs:/opt/zeppelin/logs
      - ./data:/opt/zeppelin/data
      # spark
      - /opt/spark:/opt/spark
      # mount interpreter here
      # - ./interpreter:/opt/zeppelin/interpreter
    environment:
      # - ZEPPELIN_LOG_DIR=/logs
      # - ZEPPELIN_NOTEBOOK_DIR=/notebook
      # - ZEPPELIN_LOCAL_IP=0.0.0.0
      - ZEPPELIN_JAVA_OPTS=-Dspark.driver.host=127.0.0.1 -Dspark.driver.memory=8g -Dspark.driver.cores=4 -Dspark.executor.instances=1 -Dspark.executor.cores=2 -Dspark.executor.memory=6g 
      - SPARK_HOME=/opt/spark
