---
version: '3'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi 
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9443:9443"
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=9443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin
