[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.glyph_offset]
x = -1
y = -4

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = -2
y = -7

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
